/* Copyright 2022 SiFive, Inc */
/* SPDX-License-Identifier: Apache-2.0 */

#ifndef METAL__DRIVERS__SIFIVE_HWPF1_H
#define METAL__DRIVERS__SIFIVE_HWPF1_H


#include <machine.h>

/* TwinJET and BPM enable masks */
/* Enable TwinJet if NSTREAMS != 0 */
#if defined(METAL_HWPF1_NSTREAMS) && (METAL_HWPF1_NSTREAMS != 0U)
    #define HWPFCSR_ENABLETWJ_MASK (0x1UL << HWPFCSR_ENABLETWJ_OFFSET)
#else
    #define HWPFCSR_ENABLETWJ_MASK 0x0UL
#endif

/* Enable BPM if NBPMSTREAMS != 0 */
#if defined(METAL_HWPF1_NBPMSTREAMS) && (METAL_HWPF1_NBPMSTREAMS != 0U)
    #define HWPFCSR_ENABLEBPM_MASK (0x1UL << HWPFCSR_ENABLEBPM_OFFSET)
#else
    #define HWPFCSR_ENABLEBPM_MASK 0x0UL
#endif

#define HWPFCSR_ENABLE_MASK                                                    \
    (HWPFCSR_ENABLETWJ_MASK | HWPFCSR_ENABLEBPM_MASK)

/* Fine-tuned values for each field in HWPFCSR */
#define HWPF_HWPFCSR_ENABLETWJ 0x1UL
#define HWPF_HWPFCSR_WINDOW 0x20UL
#define HWPF_HWPFCSR_DIST 0x4UL
#define HWPF_HWPFCSR_MAXALLOWEDDIST 0x1FUL
#define HWPF_HWPFCSR_LINTOEXPTHRD 0x3UL
#define HWPF_HWPFCSR_QFULLNESSTHRDL1 0xEUL
#define HWPF_HWPFCSR_HITCACHETHRDL1 0xAUL
#define HWPF_HWPFCSR_HITMSHRTHRDL1 0x2UL
#define HWPF_HWPFCSR_ISSUEBUBBLE 0x1UL
#define HWPF_HWPFCSR_MAXL1PFDIST 0x8UL
#define HWPF_HWPFCSR_NTLL1 0x0UL
#define HWPF_HWPFCSR_NUML1PFLSSQENT 0x2UL

/* BPM-specific register fields in HWPFCSR */
#if defined(METAL_HWPF1_NBPMSTREAMS) && (METAL_HWPF1_NBPMSTREAMS != 0U)
    #define HWPF_HWPFCSR_ENABLEBPM 0x1UL
    #define HWPF_HWPFCSR_FORGIVETHRD 0x6UL
    #define HWPF_HWPFCSR_FORGIVEMAXDELTA 0x4UL
#else
    #define HWPF_HWPFCSR_ENABLEBPM 0x0UL
    #define HWPF_HWPFCSR_FORGIVETHRD 0x0UL
    #define HWPF_HWPFCSR_FORGIVEMAXDELTA 0x0UL
#endif

/* Fine-tuned values for each field in HWP2FCSR */
#define HWPF_HWPF2CSR_L2PFENABLE 0x1UL
#define HWPF_HWPF2CSR_QFULLNESSTHRDL2 0xFUL
#define HWPF_HWPF2CSR_HITCACHETHRDL2 0x14UL
#define HWPF_HWPF2CSR_HITMSHRTHRDL2 0x4UL
#define HWPF_HWPF2CSR_NUML2PFLSSQENT 0x2UL

/* CSR numbers */
#define CSR_HWPFCSR 0x7c3
#define CSR_HWPF2CSR 0x7c4

void sifive_hwpf1_init(void);


#endif /* METAL__DRIVERS__SIFIVE_HWPF0_H */
