obj-$(CONFIG_PLAT_QEMU_RISCV_VIRT) += qemu-riscv-virt/
obj-$(CONFIG_PLAT_QEMU_AARCH64_VIRT) += qemu-aarch64-virt/
obj-$(CONFIG_PLAT_SG2042) += sg2042/
obj-$(CONFIG_PLAT_SG2044) += sg2044/
obj-$(CONFIG_PLAT_BM1690TP) += bm1690tp/
