obj-$(CONFIG_TEST_ARCH_TIMER) +=arch_timer/
obj-$(CONFIG_TEST_FAB) += fab/
obj-$(CONFIG_TEST_GIC) += gic/
obj-$(CONFIG_TEST_HELLO) += hello/
obj-$(CONFIG_TEST_SD) += sd/
obj-$(CONFIG_TEST_SPI_FLASH) += spi-flash/
obj-$(CONFIG_TEST_FAT32) += fat32/
obj-$(CONFIG_TEST_SMP) += smp/
obj-$(CONFIG_TEST_RISCV_EXCEPTION) += riscv_exception/
obj-$(CONFIG_TEST_BLKDEV) += blkdev/
obj-$(CONFIG_TEST_BOOTDEV) += bootdev/
obj-$(CONFIG_TEST_C2CLAT) += c2clat/
obj-$(CONFIG_TEST_MULTI_THREAD) += thread/
obj-$(CONFIG_TEST_MALLOC) += malloc/

