obj-y += boot.o
obj-y += riscv_clint0.o
obj-y += riscv_cpu.o
obj-y += sifive_buserror.o
obj-y += sifive_ccache1.o
obj-y += sifive_cpu.o
obj-y += sifive_inline.o
obj-y += sifive_interrupt.o
obj-y += sifive_l2pf2.o
obj-y += sifive_pl2cache0.o
obj-y += sifive_plic1.o
obj-y += sifive_shutdown.o

LINUXINCLUDE += -I$(srctree)/plat/x280/ \
				-I$(srctree)/plat/x280/include \
