obj-y += fat32/
obj-y += fdt/
obj-y += libc/
obj-y += debug/
obj-y += ini/
obj-y += mac/
obj-y += cli/
obj-y += hash/
obj-y += akcipher/

obj-$(CONFIG_SOPHGO_FAT_BOOT_DEVICE_FRAMEWORK) += sgfat/
obj-$(CONFIG_SOPHGO_CONFIG_BOOT_DEVICE_FRAMEWORK) += sgcfg/
obj-$(CONFIG_SOPHGO_MTD_BOOT_DEVICE_FRAMEWORK) += sgmtd/
