obj-y += fat32/
obj-y += fdt/
obj-y += libc/
obj-y += debug/

obj-$(CONFIG_SOPHGO_FAT_BOOT_DEVICE_FRAMEWORK) += sgfat/
obj-$(CONFIG_SOPHGO_CONFIG_BOOT_DEVICE_FRAMEWORK) += sgcfg/
obj-$(CONFIG_SOPHGO_MTD_BOOT_DEVICE_FRAMEWORK) += sgmtd/

