obj-$(CONFIG_DRIVER_EFUSE) += efuse/
obj-y += irqchip/
obj-y += serial/
obj-$(CONFIG_DRIVER_SPI_FLASH) += spi-flash/
obj-$(CONFIG_DRIVER_IO) += io/

obj-$(CONFIG_DRIVER_DEVICE_MODEL) += base/
obj-$(CONFIG_DRIVER_PLATFORM) += platform/
obj-$(CONFIG_DRIVER_BLOCK_DEVICE) += blkdev/
obj-$(CONFIG_DRIVER_MTD) += mtd/
obj-$(CONFIG_DRIVER_BOOT_DEVICE) += boot/

