obj-y += boot.o
obj-y += sifive_extensiblecache.o
obj-y += sifive_buserror.o
obj-y += sifive_pl2cache.o
obj-y += sifive_hwpf.o
obj-y += cpu.o
obj-y += inline.o
obj-y += soc_mode_load_img.o
obj-y += ncore_boot.o
obj-y += console.o
obj-y += cli.o
obj-y += wg.o
obj-y += iommu.o

LINUXINCLUDE += -I$(srctree)/plat/sg2380/ \
				-I$(srctree)/plat/sg2380/include \
