/* Copyright 2023 SiFive Inc. */
/* SPDX-License-Identifier: Apache-2.0 */

#include <sifive_metal.h>
#include <cpu.h>
#include <csr.h>
#include <sifive_hwpf1.h>
#include <machine.h>

void sifive_hwpf1_init(void) {
	uint64_t value;
	value = HWPF_HWPFCSR_ENABLETWJ	   << HWPFCSR_ENABLETWJ_OFFSET |
			HWPF_HWPFCSR_WINDOW		  << HWPFCSR_WINDOW_OFFSET |
			HWPF_HWPFCSR_DIST			<< HWPFCSR_DIST_OFFSET |
			HWPF_HWPFCSR_MAXALLOWEDDIST  << HWPFCSR_MAXALLOWEDDIST_OFFSET |
			HWPF_HWPFCSR_LINTOEXPTHRD	<< HWPFCSR_LINTOEXPTHRD_OFFSET |
			HWPF_HWPFCSR_QFULLNESSTHRDL1 << HWPFCSR_QFULLNESSTHRDL1_OFFSET |
			HWPF_HWPFCSR_HITCACHETHRDL1  << HWPFCSR_HITCACHETHRDL1_OFFSET |
			HWPF_HWPFCSR_HITMSHRTHRDL1   << HWPFCSR_HITMSHRTHRDL1_OFFSET |
			HWPF_HWPFCSR_ISSUEBUBBLE	 << HWPFCSR_ISSUEBUBBLE_OFFSET |
			HWPF_HWPFCSR_MAXL1PFDIST	 << HWPFCSR_MAXL1PFDIST_OFFSET |
			HWPF_HWPFCSR_NTLL1		   << HWPFCSR_NTLL1_OFFSET |
			HWPF_HWPFCSR_NUML1PFLSSQENT  << HWPFCSR_NUML1PFLSSQENT_OFFSET |
			HWPF_HWPFCSR_FORGIVETHRD	 << HWPFCSR_FORGIVETHRD_OFFSET |
			HWPF_HWPFCSR_FORGIVEMAXDELTA << HWPFCSR_FORGIVEMAXDELTA_OFFSET;

/* Disable bit-pattern hardware prefetcher for P450 and P470 */
#if defined(METAL_HWPF1_NBPMSTREAMS) && (METAL_HWPF1_NBPMSTREAMS != 0U)
	value |= HWPF_HWPFCSR_ENABLEBPM << HWPFCSR_ENABLEBPM_OFFSET;
#endif /* defined(METAL_HWPF1_NBPMSTREAMS) && (METAL_HWPF1_NBPMSTREAMS != 0U) */

	METAL_CPU_SET_CSR(CSR_HWPFCSR, value);

	value = HWPF_HWPF2CSR_L2PFENABLE	  << HWPF2CSR_L2PFENABLE_OFFSET |
			HWPF_HWPF2CSR_QFULLNESSTHRDL2 << HWPF2CSR_QFULLNESSTHRDL2_OFFSET |
			HWPF_HWPF2CSR_HITCACHETHRDL2  << HWPF2CSR_HITCACHETHRDL2_OFFSET |
			HWPF_HWPF2CSR_HITMSHRTHRDL2   << HWPF2CSR_HITMSHRTHRDL2_OFFSET |
			HWPF_HWPF2CSR_NUML2PFLSSQENT  << HWPF2CSR_NUML2PFLSSQENT_OFFSET;
	METAL_CPU_SET_CSR(CSR_HWPF2CSR, value);
}
